### ISSUE TITLE
[Bug]: Mongodb枚举+数组类型插入数据库与预期不符

### ISSUE THREAD

**Issue by Cyaim** [joesdu/EasilyNET#482]
### ⚙️ OS

None

### ⚙️ Architecture

Any(Default)

### ⚙️ .NET Version

.NET8(LTS) (Default)

### 📄 请描述您的问题(Describe the bug).

![企业微信截图_17204255594180](https://github.com/joesdu/EasilyNET/assets/28213262/4897dcab-33bf-4f71-9a9a-18932ccdbbfa)
枚举数组类型插入数据库与预期不符，应该为[兔,牛,狗]。
若为枚举类型时，数据库数据正确。

    /// <summary>
    /// 生肖
    /// </summary>
    public enum ZodiacEnum
    {
        鼠, 牛, 虎, 兔, 龙, 蛇, 马, 羊, 猴, 鸡, 狗, 猪
    }

**Comment by joesdu** [comment]
这个问题在[CSHARP-2096](https://jira.mongodb.org/browse/CSHARP-2096)有提出来,在MongoDB驱动的[PR305](https://github.com/mongodb/mongo-csharp-driver/pull/305)中有回复,[理论上是支持不了](https://github.com/mongodb/mongo-csharp-driver/pull/305#issuecomment-731475503).可以使用添加```[BsonRepresentation(BsonType.String)]```的方式实现
```csharp
file sealed class MultiEnum
{
    [BsonRepresentation(BsonType.String)]
    public EZodiac[] Zodiac { get; set; } = [EZodiac.兔, EZodiac.牛, EZodiac.狗];
}
```
